/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sistemacomercial.apresentacao.desktop;

import br.edu.ifnmg.logicaaplicacao.Pessoa;
import br.edu.ifnmg.logicaaplicacao.PessoaFisica;
import br.edu.ifnmg.logicaaplicacao.PessoaJuridica;
import br.edu.ifnmg.logicaaplicacao.PessoaJuridicaRepositorio;
import br.edu.ifnmg.logicaaplicacao.RepositorioFactory;
import br.edu.ifnmg.logicaaplicacao.PessoaRepositorio;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edlaine
 */
public class PessoaJuridicaBuscar extends javax.swing.JInternalFrame {
    PessoaJuridicaRepositorio repositorio;
    PessoaJuridica pjuridica;
    Pessoa pessoa;
    PessoaRepositorio repopessoa;
    /**
     * Creates new form PessoaFisicaEditar
     */
    public PessoaJuridicaBuscar() {
        this.repositorio = RepositorioFactory.getPessoaJuridicaRepositorio();
        this.pjuridica = new PessoaJuridica();
        
        this.repopessoa = RepositorioFactory.getPessoaRepositorio();
        this.pessoa = new Pessoa();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        bntBuscar = new javax.swing.JButton();
        btnNovaPFisica = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();

        setClosable(true);
        setTitle("Buscar Pessoa Física");
        setToolTipText("Buscar Pessoa Física.");

        lblNome.setText("Nome:");

        txtNome.setToolTipText("Insira o nome para a busca.");

        bntBuscar.setText("BUSCAR");
        bntBuscar.setToolTipText("Clique para efetuar a busca.");
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });

        btnNovaPFisica.setText("NOVO CADASTRO");
        btnNovaPFisica.setToolTipText("Clique para criar um Novo Cadastro.");
        btnNovaPFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaPFisicaActionPerformed(evt);
            }
        });

        btnLimpar.setText("LIMPAR");
        btnLimpar.setToolTipText("Clique para limpar os filtros da busca.");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Fantasia", "Razão Social", "CNPJ", "Rual", "Número", "Bairro", "Complemento", "Cidade", "Status", "Versão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResultado.setToolTipText("Dados da Pessoa Física.");
        tblResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultado);
        if (tblResultado.getColumnModel().getColumnCount() > 0) {
            tblResultado.getColumnModel().getColumn(0).setResizable(false);
            tblResultado.getColumnModel().getColumn(1).setResizable(false);
            tblResultado.getColumnModel().getColumn(2).setResizable(false);
            tblResultado.getColumnModel().getColumn(3).setResizable(false);
            tblResultado.getColumnModel().getColumn(4).setResizable(false);
            tblResultado.getColumnModel().getColumn(5).setResizable(false);
            tblResultado.getColumnModel().getColumn(6).setResizable(false);
            tblResultado.getColumnModel().getColumn(7).setResizable(false);
            tblResultado.getColumnModel().getColumn(8).setResizable(false);
            tblResultado.getColumnModel().getColumn(9).setResizable(false);
            tblResultado.getColumnModel().getColumn(10).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(lblNome)
                        .addGap(26, 26, 26)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(bntBuscar)
                        .addGap(51, 51, 51)
                        .addComponent(btnNovaPFisica)
                        .addGap(68, 68, 68)
                        .addComponent(btnLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntBuscar)
                    .addComponent(btnNovaPFisica)
                    .addComponent(btnLimpar))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaPFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPFisicaActionPerformed
        // TODO add your handling code here:
//        PessoaFisicaEditar tela = new PessoaFisicaEditar(new PessoaFisica());
//        this.getParent().add(tela);
//        tela.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_btnNovaPFisicaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Deseja realmente limpar a busca?", "Confirmação", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION){
            txtNome.setText("");
        
            //criou um modelo vazio
            DefaultTableModel modelo = new DefaultTableModel();
            //adicionando as colunas
            modelo.addColumn("ID");
            modelo.addColumn("Nome Fantasia");
            modelo.addColumn("Razão Social");
            modelo.addColumn("CNPJ");
            modelo.addColumn("Rua");
            modelo.addColumn("Número");
            modelo.addColumn("Bairro");
            modelo.addColumn("Complemento");
            modelo.addColumn("Cidade");
            modelo.addColumn("Status");
            modelo.addColumn("Versão");
            
            //adicionando os dados na tabela
            tblResultado.setModel(modelo);
            
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        // adicionando o que foi escrito no campo
        pjuridica.setNome(txtNome.getText());
        //fazendo a bsuca no rep com o filtro
        List<PessoaJuridica> resultado = repositorio.Buscar(pjuridica);
        //criou um modelo vazio
        DefaultTableModel modelo = new DefaultTableModel();
        //adicionando as colunas
        modelo.addColumn("ID");
        modelo.addColumn("Nome Fantasia");
        modelo.addColumn("Razão Social");
        modelo.addColumn("CNPJ");
        modelo.addColumn("Rua");
        modelo.addColumn("Número");
        modelo.addColumn("Bairro");
        modelo.addColumn("Complemento");
        modelo.addColumn("Cidade");
        modelo.addColumn("Status");
        modelo.addColumn("Versão");
        
        
        //adicionando as linhas
        for(PessoaJuridica p : resultado){
            Vector linha = new Vector();
            linha.add(p.getId());
            linha.add(p.getNome());
            linha.add(p.getRazaoSocial());
            linha.add(p.getCnpj());
            linha.add(p.getRua());
            linha.add(p.getNumero());
            linha.add(p.getBairro());
            linha.add(p.getComplemento());
            linha.add(p.getCidade());
            linha.add(p.getStatus());
            linha.add(p.getVersao());
            
            modelo.addRow(linha);
        }
        
        //adicionando os dados na tabela
        tblResultado.setModel(modelo);
        
    }//GEN-LAST:event_bntBuscarActionPerformed

    private void tblResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultadoMouseClicked
        // TODO add your handling code here:
        int linha = tblResultado.getSelectedRow();
        Long id = Long.parseLong(tblResultado.getValueAt(linha, 0).toString());

        PessoaJuridica pj = repositorio.Abrir(id);
//
//        PessoaFisicaEditar tela = new PessoaFisicaEditar(pf);
//        this.getParent().add(tela);
//        tela.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_tblResultadoMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovaPFisica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tblResultado;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
