/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sistemacomercial.apresentacao.desktop;

import br.edu.ifnmg.logicaaplicacao.Pessoa;
import br.edu.ifnmg.logicaaplicacao.PessoaFisica;
import br.edu.ifnmg.logicaaplicacao.PessoaFisicaRepositorio;
import br.edu.ifnmg.logicaaplicacao.PessoaJuridica;
import br.edu.ifnmg.logicaaplicacao.PessoaJuridicaRepositorio;
import br.edu.ifnmg.logicaaplicacao.RepositorioFactory;
import br.edu.ifnmg.logicaaplicacao.PessoaRepositorio;

/**
 *
 * @author edlaine
 */
public class PessoaEmailTela extends javax.swing.JInternalFrame {
    PessoaFisica pf;
    PessoaJuridica pj;
    Pessoa p;
    
    PessoaRepositorio repopessoa;
    PessoaFisicaRepositorio repofisica;
    PessoaJuridicaRepositorio repojuridica;
    /**
     * Creates new form PessoaEmail
     */
    public PessoaEmailTela() {
        this.p = new Pessoa();
        this.pf = new PessoaFisica();
        this.pj = new PessoaJuridica();
        
        this.repopessoa = RepositorioFactory.getPessoaRepositorio();
        this.repofisica = RepositorioFactory.getPessoaFisicaRepositorio();
        this.repojuridica = RepositorioFactory.getPessoaJuridicaRepositorio();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
