/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sistemacomercial.apresentacao.desktop;

import br.edu.ifnmg.logicaaplicacao.Genero;
import br.edu.ifnmg.logicaaplicacao.Pessoa;
import br.edu.ifnmg.logicaaplicacao.PessoaEmail;
import br.edu.ifnmg.logicaaplicacao.PessoaFisica;
import br.edu.ifnmg.logicaaplicacao.PessoaFisicaRepositorio;
import br.edu.ifnmg.logicaaplicacao.PessoaTelefone;
import br.edu.ifnmg.logicaaplicacao.RepositorioFactory;
import br.edu.ifnmg.logicaaplicacao.Status;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import br.edu.ifnmg.logicaaplicacao.PessoaRepositorio;
import javax.swing.DefaultListModel;

/**
 *
 * @author edlaine
 */
public class PessoaFisicaEditar extends javax.swing.JInternalFrame {
    PessoaFisica pessoaf;
    PessoaFisicaRepositorio repofisica;
    
    PessoaTelefone telefone;
    PessoaEmail email;
    
   /**
     * Creates new form PessoaFisicaEditar
     */
    public PessoaFisicaEditar(PessoaFisica pf) {
        this.repofisica = RepositorioFactory.getPessoaFisicaRepositorio();
        this.pessoaf = pf;
        
        this.telefone = new PessoaTelefone();
        this.email = new PessoaEmail();
        initComponents();
        
        this.setComponentes();
    }
    
    private void setComponentes(){      
        this.lblIDPessoa.setText(this.pessoaf.getId().toString());
        this.txtNome.setText(this.pessoaf.getNome());
        this.cbxStatus.setSelectedItem(this.pessoaf.getStatus().name());
        this.txtCPF.setText(this.pessoaf.getCpf());
        this.txtRG.setText(this.pessoaf.getRg());
        this.cbxGenero.setSelectedItem(this.pessoaf.getGenero().name());
        
        atualizarTelefones();
        atualizarEmail();
    }
    
    private void getComponentes(){
        this.pessoaf.setNome(this.txtNome.getText());
        this.pessoaf.setStatus(Status.valueOf(this.cbxStatus.getSelectedItem().toString()));
        this.pessoaf.setCpf(this.txtCPF.getText());
        this.pessoaf.setRg(this.txtRG.getText());
        this.pessoaf.setGenero(Genero.valueOf(this.cbxGenero.getSelectedItem().toString()));
        
        atualizarTelefones();
        atualizarEmail();
        
    }
    
    private void atualizarTelefones(){
        String[] tel = new String[pessoaf.getTelefones().size()];
        DefaultListModel telefones = new DefaultListModel();
        telefones.addAll(pessoaf.getTelefones());
        listTelefone.setModel(telefones);
     }
    
    private void atualizarEmail(){
        String[] email = new String[pessoaf.getEmails().size()];
        DefaultListModel emails = new DefaultListModel();
        emails.addAll(pessoaf.getEmails());
        listEmail.setModel(emails);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblIDPessoa = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        cbxStatus = new javax.swing.JComboBox<>();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnAdicionarTelefone = new javax.swing.JButton();
        btnRemoverTelefone = new javax.swing.JButton();
        btnRemoverEmail = new javax.swing.JButton();
        btnAdicionarEmail = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEmail = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTelefone = new javax.swing.JList<>();
        btnSalvar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Editar Pessoa Física");
        setToolTipText("Editar Pessoa Física.");

        lblID.setText("ID:");

        lblIDPessoa.setText("0");
        lblIDPessoa.setToolTipText("Código identificador.");

        lblNome.setText("Nome:");

        txtNome.setToolTipText("Digite o nome.");

        lblStatus.setText("Status:");

        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        cbxStatus.setToolTipText("Selecione o status.");

        lblCPF.setText("CPF:");

        txtCPF.setToolTipText("Insira o CPF.");

        lblRG.setText("RG:");

        txtRG.setToolTipText("Insira o RG.");

        lblGenero.setText("Gênero:");

        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Transgênero", "Outro" }));
        cbxGenero.setToolTipText("Selecione o gênero.");

        jLabel1.setText("CADASTRO DE TELEFONES");
        jLabel1.setToolTipText("CADASTRO DE TELEFONES");

        jLabel2.setText("CADASTRO DE EMAILS");
        jLabel2.setToolTipText("CADASTRO DE EMAILS");

        lblTelefone.setText("Telefone:");

        txtTelefone.setToolTipText("Insira o telefone.");

        lblEmail.setText("Email:");

        txtEmail.setToolTipText("Insira o email.");

        btnAdicionarTelefone.setText("ADICIONAR");
        btnAdicionarTelefone.setToolTipText("Clique para adicionar o telefone.");
        btnAdicionarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarTelefoneActionPerformed(evt);
            }
        });

        btnRemoverTelefone.setText("REMOVER");
        btnRemoverTelefone.setToolTipText("Clique para remover o telefone.");
        btnRemoverTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverTelefoneActionPerformed(evt);
            }
        });

        btnRemoverEmail.setText("REMOVER");
        btnRemoverEmail.setToolTipText("Clique para remover o email.");
        btnRemoverEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverEmailActionPerformed(evt);
            }
        });

        btnAdicionarEmail.setText("ADICIONAR");
        btnAdicionarEmail.setToolTipText("Clique para adicionar o email.");
        btnAdicionarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEmailActionPerformed(evt);
            }
        });

        listEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listEmailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listEmail);

        listTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTelefoneMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listTelefone);

        btnSalvar.setText("SALVAR");
        btnSalvar.setToolTipText("Clique para SALVAR.");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnRemover.setText("REMOVER");
        btnRemover.setToolTipText("Clique para REMOVER.");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.setToolTipText("Clique para CANCELAR.");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblIDPessoa)
                            .addGap(51, 51, 51)
                            .addComponent(lblNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblStatus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCPF)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblRG)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblGenero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTelefone)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1))
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEmail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(303, 303, 303)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnAdicionarTelefone)
                        .addGap(69, 69, 69)
                        .addComponent(btnRemoverTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarEmail)
                        .addGap(69, 69, 69)
                        .addComponent(btnRemoverEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(lblIDPessoa)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus)
                    .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRG)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenero)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarTelefone)
                    .addComponent(btnRemoverTelefone)
                    .addComponent(btnAdicionarEmail)
                    .addComponent(btnRemoverEmail))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnRemover)
                    .addComponent(btnSalvar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Deseja realmente remover o usuário atual?", "Confirmação", JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_OPTION){
            if(repofisica.Apagar(this.pessoaf)){
                
                JOptionPane.showMessageDialog(this, "Pessoa removida com sucesso!","Sucesso!",
                    JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);    
                
            } else {
                JOptionPane.showMessageDialog(this, "Aconteceu um problema ao remover os dados!","Erro!",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Operação Cancelada!","Informação!",
            JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Deseja realmente salvar os dados do Usuário?", "Confirmação", JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_OPTION){
            this.getComponentes();
            if(repofisica.Salvar(this.pessoaf)){
                JOptionPane.showMessageDialog(this, "Sucesso ao salvar!","Informação!",JOptionPane.INFORMATION_MESSAGE);
                this.setComponentes();
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao salvar!","ERRO!",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Operação Cancelada","Informação!",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnRemoverEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverEmailActionPerformed
        // TODO add your handling code here:
        this.pessoaf.removeEmail(email);
        txtEmail.setText("");
        atualizarEmail();
    }//GEN-LAST:event_btnRemoverEmailActionPerformed

    private void btnRemoverTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverTelefoneActionPerformed
        // TODO add your handling code here:
        this.pessoaf.removeTelefone(telefone);
        txtTelefone.setText("");
        atualizarTelefones();
    }//GEN-LAST:event_btnRemoverTelefoneActionPerformed

    private void btnAdicionarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTelefoneActionPerformed
        // TODO add your handling code here:
        this.telefone = new PessoaTelefone(pessoaf);
        this.telefone.setTelefone(txtTelefone.getText());
        this.pessoaf.addTelefone(telefone);
        txtTelefone.setText("");
        atualizarTelefones();
    }//GEN-LAST:event_btnAdicionarTelefoneActionPerformed

    private void btnAdicionarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEmailActionPerformed
        // TODO add your handling code here:
        this.email = new PessoaEmail(pessoaf);
        this.email.setEmail(txtEmail.getText());
        this.pessoaf.addEmail(email);
        txtEmail.setText("");
        atualizarEmail();
    }//GEN-LAST:event_btnAdicionarEmailActionPerformed

    private void listEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listEmailMouseClicked
        // TODO add your handling code here:
        int indice = listEmail.getSelectedIndex();
        this.email = listEmail.getModel().getElementAt(indice);
        txtEmail.setText( this.email.getEmail() );
    }//GEN-LAST:event_listEmailMouseClicked

    private void listTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTelefoneMouseClicked
        // TODO add your handling code here:
        //pega o indice de onde está o telefone que foi selecionado
        int indice = listTelefone.getSelectedIndex();
        //carrega o elemento que selecionei colocando dentro de telefone
        this.telefone = listTelefone.getModel().getElementAt(indice);
        //seleciona
        txtTelefone.setText( this.telefone.getTelefone() );
    }//GEN-LAST:event_listTelefoneMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarEmail;
    private javax.swing.JButton btnAdicionarTelefone;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnRemoverEmail;
    private javax.swing.JButton btnRemoverTelefone;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JComboBox<String> cbxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDPessoa;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JList<PessoaEmail> listEmail;
    private javax.swing.JList<PessoaTelefone> listTelefone;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
