/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sistemacomercial.apresentacao.desktop;

import br.edu.ifnmg.logicaaplicacao.Pessoa;
import br.edu.ifnmg.logicaaplicacao.RepositorioFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListModel;
import br.edu.ifnmg.logicaaplicacao.PessoaRepositorio;

/**
 *
 * @author edlaine
 */
public class PessoaTelefoneTela extends javax.swing.JInternalFrame {
    PessoaRepositorio repositorio;
    Pessoa pessoa;
    
    /**
     * Creates new form PessoaTelefone
     */
    public PessoaTelefoneTela() {
        this.repositorio = RepositorioFactory.getPessoaRepositorio();
        this.pessoa = new Pessoa();
        initComponents();
    }
       
//    private void preencherTelefones() {
//        pessoa.setId(Long.parseLong( txtID.getText().toString()));
//        pessoa.setNome(txtNome.getText());
//        //fazendo a bsuca no rep com o filtro
//        List<Pessoa> resultado = repositorio.Buscar(pessoa);
//        
//        DefaultTableModel modelo = new DefaultTableModel();
//        //adiciona coluna por coluna
//        modelo.addColumn("ID");
//        modelo.addColumn("Nome");
//        modelo.addColumn("Telefone");
//          
//        //para cada aluno da lista 
//        for (Pessoa pessoa: resultado){
//            //cria um vetor de linha
//            Vector linha = new Vector();
//            //adiciona linha por linha
//            linha.add(pessoa.getId());
//            linha.add(pessoa.getNome());
//            linha.add(pessoa.getTelefones());
//                        
//            //adiciona cada linha na tabela
//            modelo.addRow(linha);
//        }        
//        //adiciona o modelo que é a minha tabela na tabela da interface
//        tblTelefone.setModel(modelo);  
//    }
//    
//    private void limparTelefone(){
//        DefaultTableModel modelo = new DefaultTableModel();
//        //adiciona coluna por coluna
//        modelo.addColumn("ID");
//        modelo.addColumn("Nome");
//        modelo.addColumn("Telefone");
//        
//        tblTelefone.setModel(modelo);
//    }

    private void atualizarTelefones(){
        String[] tel = new String[pessoa.getTelefones().size()];
        tel = pessoa.getTelefones().toArray(tel);
        ListModel<String> telefones = new DefaultComboBoxModel<>(tel) ;
        listTelefone.setModel(telefones);
     }
    
    private void limparTelefones(){
        ListModel<String> telefones = new DefaultComboBoxModel<>() ;
        listTelefone.setModel(telefones);
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTelefone = new javax.swing.JList<>();

        setClosable(true);
        setTitle("Telefones");

        lblID.setText("ID:");

        lblNome.setText("Nome:");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listTelefone);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpar)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(btnLimpar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Pessoa p = new Pessoa();
        p.setId(Long.parseLong(txtID.getText().toString()));
        p.setNome(txtNome.getText());
        
        repositorio.Buscar(p);
        atualizarTelefones();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtNome.setText("");
        limparTelefones();
        
    }//GEN-LAST:event_btnLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JList<String> listTelefone;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
