/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sistemacomercial.apresentacao.desktop;

import br.edu.ifnmg.logicaaplicacao.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author edlaine
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Usuario usuario;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(Usuario u) {
        
        this.usuario = u;
        initComponents();
    }

    private TelaPrincipal() {
          
        this.usuario = new Usuario();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMBMenuGeral = new javax.swing.JMenuBar();
        JMSistema = new javax.swing.JMenu();
        JMISair = new javax.swing.JMenuItem();
        JMCadastros = new javax.swing.JMenu();
        JMIUsuario = new javax.swing.JMenuItem();
        JMIPessoaFisica = new javax.swing.JMenuItem();
        JMIPessoaJuridica = new javax.swing.JMenuItem();
        JMIProduto = new javax.swing.JMenuItem();
        jMContatos = new javax.swing.JMenu();
        JMITelefone = new javax.swing.JMenuItem();
        JMIEmails = new javax.swing.JMenuItem();
        JMTransacao = new javax.swing.JMenu();
        JMIBuscarTransacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Comercial");

        JMSistema.setText("Sistema");

        JMISair.setText("SAIR");
        JMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMISairActionPerformed(evt);
            }
        });
        JMSistema.add(JMISair);

        jMBMenuGeral.add(JMSistema);

        JMCadastros.setText("Cadastros");

        JMIUsuario.setText("Usuário");
        JMIUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIUsuarioActionPerformed(evt);
            }
        });
        JMCadastros.add(JMIUsuario);

        JMIPessoaFisica.setText("Pessoa Física");
        JMIPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIPessoaFisicaActionPerformed(evt);
            }
        });
        JMCadastros.add(JMIPessoaFisica);

        JMIPessoaJuridica.setText("Pessoa Jurídica");
        JMIPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIPessoaJuridicaActionPerformed(evt);
            }
        });
        JMCadastros.add(JMIPessoaJuridica);

        JMIProduto.setText("Produto");
        JMIProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIProdutoActionPerformed(evt);
            }
        });
        JMCadastros.add(JMIProduto);

        jMBMenuGeral.add(JMCadastros);

        jMContatos.setText("Contatos");

        JMITelefone.setText("Telefones");
        JMITelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMITelefoneActionPerformed(evt);
            }
        });
        jMContatos.add(JMITelefone);

        JMIEmails.setText("Emails");
        JMIEmails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIEmailsActionPerformed(evt);
            }
        });
        jMContatos.add(JMIEmails);

        jMBMenuGeral.add(jMContatos);

        JMTransacao.setText("Transações");

        JMIBuscarTransacao.setText("Buscar Transações");
        JMIBuscarTransacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIBuscarTransacaoActionPerformed(evt);
            }
        });
        JMTransacao.add(JMIBuscarTransacao);

        jMBMenuGeral.add(JMTransacao);

        setJMenuBar(jMBMenuGeral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMIUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIUsuarioActionPerformed
        // TODO add your handling code here:
        UsuarioBuscar tela = new UsuarioBuscar();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_JMIUsuarioActionPerformed

    private void JMIPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIPessoaFisicaActionPerformed
        // TODO add your handling code here:
        PessoaFisicaBuscar tela = new PessoaFisicaBuscar();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_JMIPessoaFisicaActionPerformed

    private void JMIPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIPessoaJuridicaActionPerformed
        // TODO add your handling code here:
        PessoaJuridicaBuscar tela = new PessoaJuridicaBuscar();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_JMIPessoaJuridicaActionPerformed

    private void JMITelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMITelefoneActionPerformed
        // TODO add your handling code here:
        PessoaTelefoneTela tela = new PessoaTelefoneTela();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_JMITelefoneActionPerformed

    private void JMIEmailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIEmailsActionPerformed
        // TODO add your handling code here:
        PessoaEmailTela tela = new PessoaEmailTela();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_JMIEmailsActionPerformed

    private void JMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMISairActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, usuario.getNome() + " deseja realmente SAIR do Sistema?", "Confirmação!",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Saiu com sucesso!", "Exit!", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false); 
        }else
            JOptionPane.showMessageDialog(this, "Operação Cancelada", "INFORMAÇÃO!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_JMISairActionPerformed

    private void JMIProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIProdutoActionPerformed
        // TODO add your handling code here:
        ProdutoBuscar tela = new ProdutoBuscar(usuario);
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_JMIProdutoActionPerformed

    private void JMIBuscarTransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIBuscarTransacaoActionPerformed
        // TODO add your handling code here:
        TransacaoBuscar tela = new TransacaoBuscar();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_JMIBuscarTransacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMCadastros;
    private javax.swing.JMenuItem JMIBuscarTransacao;
    private javax.swing.JMenuItem JMIEmails;
    private javax.swing.JMenuItem JMIPessoaFisica;
    private javax.swing.JMenuItem JMIPessoaJuridica;
    private javax.swing.JMenuItem JMIProduto;
    private javax.swing.JMenuItem JMISair;
    private javax.swing.JMenuItem JMITelefone;
    private javax.swing.JMenuItem JMIUsuario;
    private javax.swing.JMenu JMSistema;
    private javax.swing.JMenu JMTransacao;
    private javax.swing.JMenuBar jMBMenuGeral;
    private javax.swing.JMenu jMContatos;
    // End of variables declaration//GEN-END:variables
}
