/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.sistemacomercial.apresentacao.desktop;

import br.edu.ifnmg.logicaaplicacao.Pessoa;

/**
 *
 * @author edlaine
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Pessoa pessoa;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        pessoa = new Pessoa();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        JSistema = new javax.swing.JMenu();
        JCadastros = new javax.swing.JMenu();
        JMIUsuario = new javax.swing.JMenuItem();
        JMIPessoaFisica = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        JMITelefone = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Comercial");

        JSistema.setText("Sistema");
        jMenuBar1.add(JSistema);

        JCadastros.setText("Cadastros");

        JMIUsuario.setText("Usuário");
        JMIUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIUsuarioActionPerformed(evt);
            }
        });
        JCadastros.add(JMIUsuario);

        JMIPessoaFisica.setText("Pessoa Física");
        JMIPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIPessoaFisicaActionPerformed(evt);
            }
        });
        JCadastros.add(JMIPessoaFisica);

        jMenuBar1.add(JCadastros);

        jMenu1.setText("Contatos");

        JMITelefone.setText("Telefones");
        JMITelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMITelefoneActionPerformed(evt);
            }
        });
        jMenu1.add(JMITelefone);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMIUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIUsuarioActionPerformed
        // TODO add your handling code here:
        UsuarioBuscar tela = new UsuarioBuscar();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_JMIUsuarioActionPerformed

    private void JMIPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIPessoaFisicaActionPerformed
        // TODO add your handling code here:
        PessoaFisicaBuscar tela = new PessoaFisicaBuscar();
        this.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_JMIPessoaFisicaActionPerformed

    private void JMITelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMITelefoneActionPerformed
        // TODO add your handling code here:
        PessoaTelefoneTela tela = new PessoaTelefoneTela(new Pessoa());
        tela.getParent().add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_JMITelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JCadastros;
    private javax.swing.JMenuItem JMIPessoaFisica;
    private javax.swing.JMenuItem JMITelefone;
    private javax.swing.JMenuItem JMIUsuario;
    private javax.swing.JMenu JSistema;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
